export interface Taza{
    id:number,
    tipo_taza: string,
    color: string, 
    dimensiones: string, 
    capacidad: string,
    modelo:string ,
    material: string,
    cantidad_total: number,
    cantidad_disponible: number,
    precio_compra: number ,
    precio_venta: number,
    precio_final_compra: number,
    eliminado: boolean,
}